[package]
name = "get_cnip"
version = "7.0.0"
authors = ["Bruce Wayne <admin@bige0.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "^0.11.3"
tokio = { version = "^1.8.0", features = ["full"] }
serde = "~1.0.125"
serde_json = "~1.0.64"
